# Generated by Django 6.0 on 2025-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_price_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
