# Generated by Django 6.0 on 2025-12-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
